##-------------------INFO------------------##
#ENCRYPTED BY : U7P4L IN
# VERSION : 0.3
# OWNER OF ANONYMOUS CYBER
# FEEL THE POWER OF U7P4L IN
# GITHUB : https://github.com/U7P4L-IN
##----------------MAIN>MENU----------------##

z="
";LCz='t -y';qBz='six';mBz='ests';bz='-y';yz=' -y';ABz='php ';pBz='ls';TBz='-obj';eCz='n," ';TCz=''\''WEL';PCz='4L  ';Rz='etup';nBz='setu';BCz='dl';HBz='cert';WCz=' "No';jBz='pyli';aCz='x Is';uz='cmat';Uz='pkg ';KCz='proo';LBz='colo';vz='rix ';cCz='dy T';QBz='isor';wBz='l';uBz='ib3';fBz='dest';lz='ic -';hBz='pyfi';XBz='at';Hz='ownl';VBz='prox';Lz='upda';Gz='ge D';gz='kint';dCz='o Ru';bCz=' Rea';DCz='aniz';aBz='Pill';cz='on-s';kz='stat';Vz='inst';Wz='all ';rz='git ';cBz='pilo';tBz='urll';JBz='char';MCz='f sl';yBz='yout';RCz='|lol';OBz='re';Kz='apt ';PBz='idna';SBz='lazy';xBz='wrap';CCz='mech';UBz='ect-';WBz='lolc';Dz='or A';sBz='toml';ZCz='ermu';YCz='ur T';Pz='term';UCz='LCOM';KBz='det';lBz='requ';MBz='rama';ez='c -y';OCz=''\''U7P';kBz='nt';qz='n -y';RBz='t';az='on2 ';hz='er -';Iz='oad.';Mz='te';sz='figl';Tz='rage';Az='echo';YBz='mcca';tz='et -';Ez='ll P';SCz='cat';GCz='open';VCz='E'\'' |';iBz='glet';ICz='wget';jz='on2-';mz='weec';FCz='ruby';BBz='fish';Jz='"';ACz='ube-';gBz='yle';Sz='-sto';IBz='ifi';Zz='y';CBz='pip ';ECz='e';GBz='pep8';EBz='oid';Oz='ade';FBz='auto';nz='hat-';Fz='acka';dBz='pip';rBz='r';Yz='on -';ZBz='be';iz='vim-';Qz='ux-s';bBz='ow';QCz='IN'\'' ';HCz='ssh ';vBz='whee';Cz='it F';dz='tati';DBz='astr';xz='nano';Nz='upgr';fz='on-t';oBz='ptoo';pz='lugi';JCz='curl';Xz='pyth';XCz='w Yo';wz='toil';eBz='pyco';NCz='ant ';oz='on-p';Bz=' "Wa';NBz='futu';
eval "$Az$z$Az$z$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$z$Az$z$Az$z$Az$z$Kz$Lz$Mz$z$Kz$Nz$Oz$z$Pz$Qz$Rz$Sz$Tz$z$Uz$Vz$Wz$Xz$Yz$Zz$z$Uz$Vz$Wz$Xz$az$bz$z$Uz$Vz$Wz$Xz$cz$dz$ez$z$Uz$Vz$Wz$Xz$fz$gz$hz$Zz$z$Uz$Vz$Wz$iz$Xz$Yz$Zz$z$Uz$Vz$Wz$Xz$jz$kz$lz$Zz$z$Uz$Vz$Wz$mz$nz$Xz$oz$pz$qz$z$Uz$Vz$Wz$rz$bz$z$Uz$Vz$Wz$sz$tz$Zz$z$Uz$Vz$Wz$uz$vz$bz$z$Uz$Vz$Wz$wz$tz$Zz$z$Uz$Vz$Wz$xz$yz$z$Uz$Vz$Wz$ABz$bz$z$Uz$Vz$Wz$BBz$yz$z$CBz$Vz$Wz$DBz$EBz$z$CBz$Vz$Wz$FBz$GBz$z$CBz$Vz$Wz$HBz$IBz$z$CBz$Vz$Wz$JBz$KBz$z$CBz$Vz$Wz$LBz$MBz$z$CBz$Vz$Wz$NBz$OBz$z$CBz$Vz$Wz$PBz$z$CBz$Vz$Wz$QBz$RBz$z$CBz$Vz$Wz$SBz$TBz$UBz$VBz$Zz$z$CBz$Vz$Wz$WBz$XBz$z$CBz$Vz$Wz$YBz$ZBz$z$CBz$Vz$Wz$aBz$bBz$z$CBz$Vz$Wz$cBz$z$CBz$Vz$Wz$dBz$z$CBz$Vz$Wz$eBz$fBz$gBz$z$CBz$Vz$Wz$hBz$iBz$z$CBz$Vz$Wz$jBz$kBz$z$CBz$Vz$Wz$lBz$mBz$z$CBz$Vz$Wz$nBz$oBz$pBz$z$CBz$Vz$Wz$qBz$z$CBz$Vz$Wz$Pz$LBz$rBz$z$CBz$Vz$Wz$sBz$z$CBz$Vz$Wz$tBz$uBz$z$CBz$Vz$Wz$vBz$wBz$z$CBz$Vz$Wz$xBz$RBz$z$CBz$Vz$Wz$yBz$ACz$BCz$z$CBz$Vz$Wz$CCz$DCz$ECz$z$Kz$Vz$Wz$FCz$yz$z$Kz$Vz$Wz$GCz$HCz$bz$z$Kz$Vz$Wz$ICz$yz$z$Kz$Vz$Wz$JCz$yz$z$Kz$Vz$Wz$KCz$LCz$z$sz$tz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$z$Az$z$Az$z$Az$z$sz$tz$MCz$NCz$TCz$UCz$VCz$WBz$XBz$z$Az$z$Az$z$Az$z$Az$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$RCz$SCz"